<a href="https://colab.research.google.com/github/taimoorsardar/Machine-Learning-Projects/blob/main/StudentPlacementClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

#1. Data Exploration and Preprocessing:

In [ ]:
train_df = pd.read_excel("/content/01 Train Data.xlsx")
test_df = pd.read_excel("/content/02 Test Data.xlsx")

In [ ]:
train_df.head()

,First Name,Email ID,Quantity,Price Tier,Ticket Type,Attendee #,Group,Order Type,Currency,Total Paid,...,Attendee Status,College Name,How did you come to know about this event?,"Specify in ""Others"" (how did you come to know about this event)",Designation,Year of Graduation,CGPA,Speaking Skills,ML Knowledge,Placement Status
0,ANIKET,aniket@xyz.com,1,NaN,Art of Resume Building,2.213855e+09,NaN,Free Order,USD,0,...,Attending,D Y PATIL INSTITUTE OF MCA AND MANAGEMENT AKUR...,Email,NaN,Students,NaN,6.7,2,5,Placed
1,Dhanshree,dhanshree@xyz.com,1,NaN,Art of Resume Building,2.213859e+09,NaN,Free Order,USD,0,...,Attending,AP SHAH INSTITUTE OF TECHNOLOGY,Others,College,Students,NaN,8.2,3,2,Not placed
2,Dhiraj,dhiraj@xyz.com,1,NaN,Art of Resume Building,2.213862e+09,NaN,Free Order,USD,0,...,Attending,Don Bosco College of Engineering Fatorda Goa,Email,NaN,Students,NaN,6.5,4,3,Not placed
3,Pooja,pooja@xyz.com,1,NaN,Art of Resume Building,2.213988e+09,NaN,Free Order,USD,0,...,Attending,Pillai College of Engineering New Panvel,Email,NaN,Students,NaN,8.7,2,5,Not placed
4,Aayush,aayush@xyz.com,1,NaN,Art of Resume Building,2.214567e+09,NaN,Free Order,USD,0,...,Attending,St Xavier's College,Instagram | LinkedIn | Cloud Counselage Website,NaN,Students,NaN,9.1,3,5,Placed

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4894 entries, 0 to 4893
Data columns (total 23 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   First Name                                                       4894 non-null   object
 1   Email ID                                                         4894 non-null   object
 2   Quantity                                                         4894 non-null   int64
 3   Price Tier                                                       0 non-null      float64
 4   Ticket Type                                                      4894 non-null   object
 5   Attendee #                                                       4490 non-null   float64
 6   Group                                                            0 non-null      float64
 7   Order Type                                                       4894 non-null   object
 8   Currency                                                         4490 non-null   object
 9   Total Paid                                                       4894 non-null   int64
 10  Fees Paid                                                        4490 non-null   float64
 11  Eventbrite Fees                                                  4894 non-null   int64
 12  Eventbrite Payment Processing                                    4894 non-null   int64
 13  Attendee Status                                                  4894 non-null   object
 14  College Name                                                     4879 non-null   object
 15  How did you come to know about this event?                       2678 non-null   object
 16  Specify in "Others" (how did you come to know about this event)  89 non-null     object
 17  Designation                                                      4894 non-null   object
 18  Year of Graduation                                               1032 non-null   object
 19  CGPA                                                             4894 non-null   float64
 20  Speaking Skills                                                  4894 non-null   int64
 21  ML Knowledge                                                     4894 non-null   int64
 22  Placement Status                                                 1098 non-null   object
dtypes: float64(5), int64(6), object(12)
memory usage: 879.5+ KB

In [ ]:
test_df.head()

,First Name,Email ID,Quantity,Price Tier,Ticket Type,Attendee #,Group,Order Type,Currency,Total Paid,...,Attendee Status,College Name,How did you come to know about this event?,"Specify in ""Others"" (how did you come to know about this event)",Designation,Year of Graduation,CGPA,Speaking Skills,ML Knowledge,Placement Status
0,Sahil,sahil@xyz.com,1,NaN,Hello ML and DL,2.293940e+09,NaN,Free Order,USD,0,...,Attending,"symbiosis institute of technology, pune",Whatsapp,NaN,Students,NaN,7.8,3,3,NaN
1,Amrita,amrita@xyz.com,1,NaN,Hello ML and DL,2.293941e+09,NaN,Free Order,USD,0,...,Attending,"mit academy of engineering ,alandi",Whatsapp,NaN,Students,NaN,9.1,3,3,NaN
2,Mamta,mamta@xyz.com,1,NaN,Hello ML and DL,2.293941e+09,NaN,Free Order,USD,0,...,Attending,a. c. patil college of engineering,Whatsapp,NaN,Students,NaN,6.9,2,2,NaN
3,Bhagyashri,bhagyashri@xyz.com,1,NaN,Hello ML and DL,2.293946e+09,NaN,Free Order,USD,0,...,Attending,wilson college,Others,NaN,Students,NaN,8.4,4,4,NaN
4,Divyanshu,divyanshu@xyz.com,1,NaN,Hello ML and DL,2.293956e+09,NaN,Free Order,USD,0,...,Attending,"ld college of engineering, ahmedabad, gujarat",Whatsapp,NaN,Students,NaN,6.7,5,5,NaN

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3796 entries, 0 to 3795
Data columns (total 23 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   First Name                                                       3796 non-null   object
 1   Email ID                                                         3796 non-null   object
 2   Quantity                                                         3796 non-null   int64
 3   Price Tier                                                       0 non-null      float64
 4   Ticket Type                                                      3796 non-null   object
 5   Attendee #                                                       3794 non-null   float64
 6   Group                                                            0 non-null      float64
 7   Order Type                                                       3796 non-null   object
 8   Currency                                                         3794 non-null   object
 9   Total Paid                                                       3796 non-null   int64
 10  Fees Paid                                                        3794 non-null   float64
 11  Eventbrite Fees                                                  3796 non-null   int64
 12  Eventbrite Payment Processing                                    3796 non-null   int64
 13  Attendee Status                                                  3796 non-null   object
 14  College Name                                                     3795 non-null   object
 15  How did you come to know about this event?                       1584 non-null   object
 16  Specify in "Others" (how did you come to know about this event)  27 non-null     object
 17  Designation                                                      3796 non-null   object
 18  Year of Graduation                                               1032 non-null   object
 19  CGPA                                                             3796 non-null   float64
 20  Speaking Skills                                                  3796 non-null   int64
 21  ML Knowledge                                                     3796 non-null   int64
 22  Placement Status                                                 0 non-null      float64
dtypes: float64(6), int64(6), object(11)
memory usage: 682.2+ KB

In [ ]:
train_missing = train_df.isnull().sum()
test_missing = test_df.isnull().sum()
train_missing

First Name                                                            0
Email ID                                                              0
Quantity                                                              0
Price Tier                                                         4894
Ticket Type                                                           0
Attendee #                                                          404
Group                                                              4894
Order Type                                                            0
Currency                                                            404
Total Paid                                                            0
Fees Paid                                                           404
Eventbrite Fees                                                       0
Eventbrite Payment Processing                                         0
Attendee Status                                                       0
College Name                                                         15
How did you come to know about this event?                         2216
Specify in "Others" (how did you come to know about this event)    4805
Designation                                                           0
Year of Graduation                                                 3862
CGPA                                                                  0
Speaking Skills                                                       0
ML Knowledge                                                          0
Placement Status                                                   3796
dtype: int64

In [ ]:
test_missing

First Name                                                            0
Email ID                                                              0
Quantity                                                              0
Price Tier                                                         3796
Ticket Type                                                           0
Attendee #                                                            2
Group                                                              3796
Order Type                                                            0
Currency                                                              2
Total Paid                                                            0
Fees Paid                                                             2
Eventbrite Fees                                                       0
Eventbrite Payment Processing                                         0
Attendee Status                                                       0
College Name                                                          1
How did you come to know about this event?                         2212
Specify in "Others" (how did you come to know about this event)    3769
Designation                                                           0
Year of Graduation                                                 2764
CGPA                                                                  0
Speaking Skills                                                       0
ML Knowledge                                                          0
Placement Status                                                   3796
dtype: int64

In [ ]:
# Drop columns with a high proportion of missing values
columns_to_drop = ['First Name','Email ID','Price Tier', 'Group', 'Specify in "Others" (how did you come to know about this event)']
train_df_cleaned = train_df.drop(columns=columns_to_drop)
test_df_cleaned = test_df.drop(columns=columns_to_drop)

In [ ]:
# Fill missing values in categorical columns with the mode
categorical_columns = ['College Name', 'How did you come to know about this event?', 'Year of Graduation']
for col in categorical_columns:
    train_df_cleaned[col].fillna(train_df_cleaned[col].mode()[0], inplace=True)
    test_df_cleaned[col].fillna(test_df_cleaned[col].mode()[0], inplace=True)

# Fill missing values in numerical columns with the median
numerical_columns = ['Attendee #', 'Fees Paid']
for col in numerical_columns:
    train_df_cleaned[col].fillna(train_df_cleaned[col].median(), inplace=True)
    test_df_cleaned[col].fillna(test_df_cleaned[col].median(), inplace=True)

In [ ]:
# Check for any remaining missing values
train_missing_after_cleaning = train_df_cleaned.isnull().sum()
test_missing_after_cleaning = test_df_cleaned.isnull().sum()

# Output the missing values after cleaning
print("Missing values in the training data after cleaning:")
print(train_missing_after_cleaning)
print("\nMissing values in the test data after cleaning:")
print(test_missing_after_cleaning)

Missing values in the training data after cleaning:
Quantity                                         0
Ticket Type                                      0
Attendee #                                       0
Order Type                                       0
Currency                                       404
Total Paid                                       0
Fees Paid                                        0
Eventbrite Fees                                  0
Eventbrite Payment Processing                    0
Attendee Status                                  0
College Name                                     0
How did you come to know about this event?       0
Designation                                      0
Year of Graduation                               0
CGPA                                             0
Speaking Skills                                  0
ML Knowledge                                     0
Placement Status                              3796
dtype: int64

Missing values in the test data after cleaning:
Quantity                                         0
Ticket Type                                      0
Attendee #                                       0
Order Type                                       0
Currency                                         2
Total Paid                                       0
Fees Paid                                        0
Eventbrite Fees                                  0
Eventbrite Payment Processing                    0
Attendee Status                                  0
College Name                                     0
How did you come to know about this event?       0
Designation                                      0
Year of Graduation                               0
CGPA                                             0
Speaking Skills                                  0
ML Knowledge                                     0
Placement Status                              3796
dtype: int64

In [ ]:
train_df_cleaned.head()

,Quantity,Ticket Type,Attendee #,Order Type,Currency,Total Paid,Fees Paid,Eventbrite Fees,Eventbrite Payment Processing,Attendee Status,College Name,How did you come to know about this event?,Designation,Year of Graduation,CGPA,Speaking Skills,ML Knowledge,Placement Status
0,1,Art of Resume Building,2.213855e+09,Free Order,USD,0,0.0,0,0,Attending,D Y PATIL INSTITUTE OF MCA AND MANAGEMENT AKUR...,Email,Students,2021,6.7,2,5,Placed
1,1,Art of Resume Building,2.213859e+09,Free Order,USD,0,0.0,0,0,Attending,AP SHAH INSTITUTE OF TECHNOLOGY,Others,Students,2021,8.2,3,2,Not placed
2,1,Art of Resume Building,2.213862e+09,Free Order,USD,0,0.0,0,0,Attending,Don Bosco College of Engineering Fatorda Goa,Email,Students,2021,6.5,4,3,Not placed
3,1,Art of Resume Building,2.213988e+09,Free Order,USD,0,0.0,0,0,Attending,Pillai College of Engineering New Panvel,Email,Students,2021,8.7,2,5,Not placed
4,1,Art of Resume Building,2.214567e+09,Free Order,USD,0,0.0,0,0,Attending,St Xavier's College,Instagram | LinkedIn | Cloud Counselage Website,Students,2021,9.1,3,5,Placed

In [ ]:
# Encode the target variable
train_df_cleaned['Placement Status'] = train_df_cleaned['Placement Status'].map({'Placed': 1, 'Not placed': 0})
# List of categorical features to encode
categorical_features = [
    'Ticket Type', 'Order Type', 'Currency', 'Attendee Status', 'College Name',
    'How did you come to know about this event?', 'Designation', 'Year of Graduation'
]

# Apply one-hot encoding
train_df_encoded = pd.get_dummies(train_df_cleaned, columns=categorical_features, drop_first=True)
test_df_encoded = pd.get_dummies(test_df_cleaned, columns=categorical_features, drop_first=True)

In [ ]:
# Separate the target variable from the training dataset before alignment
placement_status = train_df_cleaned['Placement Status']

# Align the training and test datasets
#train_df_encoded, test_df_encoded = train_df_encoded.align(test_df_encoded, join='inner', axis=1)

# Add the target variable back to the training dataset
train_df_encoded['Placement Status'] = placement_status

# Check the final structure
print(train_df_encoded.head())
print(test_df_encoded.head())

   Quantity    Attendee #  Total Paid  Fees Paid  Eventbrite Fees  \
0         1  2.213855e+09           0        0.0                0
1         1  2.213859e+09           0        0.0                0
2         1  2.213862e+09           0        0.0                0
3         1  2.213988e+09           0        0.0                0
4         1  2.214567e+09           0        0.0                0

   Eventbrite Payment Processing  CGPA  Speaking Skills  ML Knowledge  \
0                              0   6.7                2             5
1                              0   8.2                3             2
2                              0   6.5                4             3
3                              0   8.7                2             5
4                              0   9.1                3             5

   Placement Status  ...  Year of Graduation_BR  \
0               1.0  ...                  False
1               0.0  ...                  False
2               0.0  ...                  False
3               0.0  ...                  False
4               1.0  ...                  False

   Year of Graduation_Bachelor of Engineering   Year of Graduation_Final Year  \
0                                        False                          False
1                                        False                          False
2                                        False                          False
3                                        False                          False
4                                        False                          False

   Year of Graduation_Fourth Year  Year of Graduation_Friend  \
0                           False                      False
1                           False                      False
2                           False                      False
3                           False                      False
4                           False                      False

   Year of Graduation_Last Year  Year of Graduation_Pursuing  \
0                         False                        False
1                         False                        False
2                         False                        False
3                         False                        False
4                         False                        False

   Year of Graduation_Second year  Year of Graduation_Third year  \
0                           False                          False
1                           False                          False
2                           False                          False
3                           False                          False
4                           False                          False

   Year of Graduation_i am student in 12 commerce
0                                           False
1                                           False
2                                           False
3                                           False
4                                           False

[5 rows x 257 columns]
   Quantity    Attendee #  Total Paid  Fees Paid  Eventbrite Fees  \
0         1  2.293940e+09           0        0.0                0
1         1  2.293941e+09           0        0.0                0
2         1  2.293941e+09           0        0.0                0
3         1  2.293946e+09           0        0.0                0
4         1  2.293956e+09           0        0.0                0

   Eventbrite Payment Processing  CGPA  Speaking Skills  ML Knowledge  \
0                              0   7.8                3             3
1                              0   9.1                3             3
2                              0   6.9                2             2
3                              0   8.4                4             4
4                              0   6.7                5             5

   Placement Status  ...  Year of Graduation_BR  \
0               NaN  ...                  False
1               NaN  ...                  False
2               NaN  ...                  False
3               NaN  ...                  False
4               NaN  ...                  False

   Year of Graduation_Bachelor of Engineering   Year of Graduation_Final Year  \
0                                        False                          False
1                                        False                          False
2                                        False                          False
3                                        False                          False
4                                        False                          False

   Year of Graduation_Fourth Year  Year of Graduation_Friend  \
0                           False                      False
1                           False                      False
2                           False                      False
3                           False                      False
4                           False                      False

   Year of Graduation_Last Year  Year of Graduation_Pursuing  \
0                         False                        False
1                         False                        False
2                         False                        False
3                         False                        False
4                         False                        False

   Year of Graduation_Second year  Year of Graduation_Third year  \
0                           False                          False
1                           False                          False
2                           False                          False
3                           False                          False
4                           False                          False

   Year of Graduation_i am student in 12 commerce
0                                           False
1                                           False
2                                           False
3                                           False
4                                           False

[5 rows x 239 columns]

In [ ]:
train_df_encoded.head()

,Quantity,Attendee #,Total Paid,Fees Paid,Eventbrite Fees,Eventbrite Payment Processing,CGPA,Speaking Skills,ML Knowledge,Placement Status,...,Year of Graduation_BR,Year of Graduation_Bachelor of Engineering,Year of Graduation_Final Year,Year of Graduation_Fourth Year,Year of Graduation_Friend,Year of Graduation_Last Year,Year of Graduation_Pursuing,Year of Graduation_Second year,Year of Graduation_Third year,Year of Graduation_i am student in 12 commerce
0,1,2.213855e+09,0,0.0,0,0,6.7,2,5,1.0,...,False,False,False,False,False,False,False,False,False,False
1,1,2.213859e+09,0,0.0,0,0,8.2,3,2,0.0,...,False,False,False,False,False,False,False,False,False,False
2,1,2.213862e+09,0,0.0,0,0,6.5,4,3,0.0,...,False,False,False,False,False,False,False,False,False,False
3,1,2.213988e+09,0,0.0,0,0,8.7,2,5,0.0,...,False,False,False,False,False,False,False,False,False,False
4,1,2.214567e+09,0,0.0,0,0,9.1,3,5,1.0,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
test_df_encoded.head()

,Quantity,Attendee #,Total Paid,Fees Paid,Eventbrite Fees,Eventbrite Payment Processing,CGPA,Speaking Skills,ML Knowledge,Placement Status,...,Year of Graduation_BR,Year of Graduation_Bachelor of Engineering,Year of Graduation_Final Year,Year of Graduation_Fourth Year,Year of Graduation_Friend,Year of Graduation_Last Year,Year of Graduation_Pursuing,Year of Graduation_Second year,Year of Graduation_Third year,Year of Graduation_i am student in 12 commerce
0,1,2.293940e+09,0,0.0,0,0,7.8,3,3,NaN,...,False,False,False,False,False,False,False,False,False,False
1,1,2.293941e+09,0,0.0,0,0,9.1,3,3,NaN,...,False,False,False,False,False,False,False,False,False,False
2,1,2.293941e+09,0,0.0,0,0,6.9,2,2,NaN,...,False,False,False,False,False,False,False,False,False,False
3,1,2.293946e+09,0,0.0,0,0,8.4,4,4,NaN,...,False,False,False,False,False,False,False,False,False,False
4,1,2.293956e+09,0,0.0,0,0,6.7,5,5,NaN,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
train_df_encoded['Placement Status']

0       1.0
1       0.0
2       0.0
3       0.0
4       1.0
       ...
4889    NaN
4890    NaN
4891    NaN
4892    NaN
4893    NaN
Name: Placement Status, Length: 4894, dtype: float64

In [ ]:
# Check how many rows have NaN in 'Placement Status'
nan_count = train_df_encoded['Placement Status'].isna().sum()
print(f"Number of rows with NaN in 'Placement Status': {nan_count}")

Number of rows with NaN in 'Placement Status': 3796

In [ ]:
# remove those rows
train_df_encoded_cleaned = train_df_encoded.dropna(subset=['Placement Status'])
print(train_df_encoded_cleaned['Placement Status'].isna().sum())  # Should output 0

0

In [ ]:
# Get missing columns in the training set
missing_cols_train = set(test_df_encoded.columns) - set(train_df_encoded.columns)

# Add a missing column in test set with default value equal to 0
for c in missing_cols_train:
    train_df_encoded[c] = 0

# Get missing columns in the testing set
missing_cols_test = set(train_df_encoded.columns) - set(test_df_encoded.columns)

# Add a missing column in test set with default value equal to 0
for c in missing_cols_test:
    test_df_encoded[c] = 0

# Ensure the order of column in the test set is in the same order than in train set
test_df_encoded = test_df_encoded[train_df_encoded.columns]

In [ ]:
train_df = train_df_encoded_cleaned
test_df = test_df_encoded

#2. Model Development:

In [ ]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
# Separate features and target variable
X = train_df.drop('Placement Status', axis=1)
y = train_df['Placement Status']

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred_logreg = logreg.predict(X_val)
print("Logistic Regression:")
print("Accuracy:", accuracy_score(y_val, y_pred_logreg))
print(classification_report(y_val, y_pred_logreg))

Logistic Regression:
Accuracy: 0.6045454545454545
              precision    recall  f1-score   support

         0.0       0.60      1.00      0.75       133
         1.0       0.00      0.00      0.00        87

    accuracy                           0.60       220
   macro avg       0.30      0.50      0.38       220
weighted avg       0.37      0.60      0.46       220

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_val)
print("\nDecision Tree:")
print("Accuracy:", accuracy_score(y_val, y_pred_tree))
print(classification_report(y_val, y_pred_tree))

# 3. Random Forest
rf = RandomForestClassifier()
param_grid_rf = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10]
}
grid_search_rf = GridSearchCV(rf, param_grid_rf, cv=5)
grid_search_rf.fit(X_train, y_train)
print("\nRandom Forest - Best Parameters:", grid_search_rf.best_params_)
y_pred_rf = grid_search_rf.predict(X_val)
print("Accuracy:", accuracy_score(y_val, y_pred_rf))
print(classification_report(y_val, y_pred_rf))

# 4. Gradient Boosting
gb = GradientBoostingClassifier()
param_dist_gb = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7]
}
random_search_gb = RandomizedSearchCV(gb, param_dist_gb, n_iter=10, cv=5)
random_search_gb.fit(X_train, y_train)
print("\nGradient Boosting - Best Parameters:", random_search_gb.best_params_)
y_pred_gb = random_search_gb.predict(X_val)
print("Accuracy:", accuracy_score(y_val, y_pred_gb))
print(classification_report(y_val, y_pred_gb))

Decision Tree:
Accuracy: 0.4727272727272727
              precision    recall  f1-score   support

         0.0       0.55      0.65      0.60       133
         1.0       0.27      0.20      0.23        87

    accuracy                           0.47       220
   macro avg       0.41      0.42      0.41       220
weighted avg       0.44      0.47      0.45       220


Random Forest - Best Parameters: {'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 100}
Accuracy: 0.5954545454545455
              precision    recall  f1-score   support

         0.0       0.60      0.98      0.75       133
         1.0       0.00      0.00      0.00        87

    accuracy                           0.60       220
   macro avg       0.30      0.49      0.37       220
weighted avg       0.36      0.60      0.45       220


Gradient Boosting - Best Parameters: {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.01}
Accuracy: 0.5909090909090909
              precision    recall  f1-score   support

         0.0       0.60      0.98      0.74       133
         1.0       0.00      0.00      0.00        87

    accuracy                           0.59       220
   macro avg       0.30      0.49      0.37       220
weighted avg       0.36      0.59      0.45       220

#3. Evaluation and Validation:

In [ ]:
from sklearn.model_selection import cross_val_score

cv_scores_logreg = cross_val_score(logreg, X, y, cv=5)
print("\nLogistic Regression - Cross-validation scores:", cv_scores_logreg)
print("Mean CV Accuracy:", cv_scores_logreg.mean())

cv_scores_tree = cross_val_score(tree, X, y, cv=5)
print("\nDecision Tree - Cross-validation scores:", cv_scores_tree)
print("Mean CV Accuracy:", cv_scores_tree.mean())

best_rf = RandomForestClassifier(**grid_search_rf.best_params_)
best_rf.fit(X_train, y_train)
cv_scores_rf = cross_val_score(best_rf, X, y, cv=5)
print("\nRandom Forest - Cross-validation scores:", cv_scores_rf)
print("Mean CV Accuracy:", cv_scores_rf.mean())

best_gb = GradientBoostingClassifier(**random_search_gb.best_params_)
best_gb.fit(X_train, y_train)
cv_scores_gb = cross_val_score(best_gb, X, y, cv=5)
print("\nGradient Boosting - Cross-validation scores:", cv_scores_gb)
print("Mean CV Accuracy:", cv_scores_gb.mean())

print("\nChecking for Overfitting:")
print("Logistic Regression - Training Accuracy:", logreg.score(X_train, y_train))
print("Decision Tree - Training Accuracy:", tree.score(X_train, y_train))
print("Random Forest - Training Accuracy:", best_rf.score(X_train, y_train))
print("Gradient Boosting - Training Accuracy:", best_gb.score(X_train, y_train))

Logistic Regression - Cross-validation scores: [0.66363636 0.66818182 0.66818182 0.66666667 0.66666667]
Mean CV Accuracy: 0.6666666666666666

Decision Tree - Cross-validation scores: [0.54545455 0.57272727 0.53181818 0.5890411  0.40639269]
Mean CV Accuracy: 0.5290867579908676

Random Forest - Cross-validation scores: [0.65909091 0.66818182 0.66818182 0.66666667 0.64840183]
Mean CV Accuracy: 0.6621046077210461

Gradient Boosting - Cross-validation scores: [0.65       0.66363636 0.66363636 0.66666667 0.65296804]
Mean CV Accuracy: 0.659381486093815

Checking for Overfitting:
Logistic Regression - Training Accuracy: 0.6822323462414579
Decision Tree - Training Accuracy: 0.9988610478359908
Random Forest - Training Accuracy: 0.6913439635535308
Gradient Boosting - Training Accuracy: 0.6913439635535308

Decision Tree outperforms them all

#4. Prediction and Submission:

In [ ]:
import pandas as pd
# Remove the target variable from the test data
test_data_without_target = test_df.drop('Placement Status', axis=1)

test_predictions = tree.predict(test_data_without_target)

# Create a DataFrame for submission
submission_df = pd.DataFrame({
    'Attendee #': test_df['Attendee #'],
    'Placement Status': test_predictions
})

# Map predictions back to original labels if necessary
submission_df['Placement Status'] = submission_df['Placement Status'].map({1: 'Placed', 0: 'Not placed'})

# Save predictions to an Excel file
submission_df.to_excel('predictions.xlsx', index=False)